CUDA_DIR    = /usr/local/cuda
CUDA_LIB    = $(CUDA_DIR)/lib64
CUDA_INC    = $(CUDA_DIR)/include

CPP         = g++
CPP_FLAGS   = -MD -c -g -O2 -Wall -I$(CUDA_INC)
NVCC        = nvcc
NVCC_BFLAGS = -g -cudart=shared 
NVCC_FLAGS  = -c $(NVCC_BFLAGS)
CPPNV_BFLAGS= -g -O2 -Wall
CPPNV_FLAGS = -c $(CPPNV_BFLAGS)
BEG_X_FLAGS = -Xcompiler="
END_X_FLAGS = "
INC_COMMON  = -I$(shell pwd)/../common
LD          = g++
CULD        = nvcc

RM          = rm
RM_FLAGS    = -f

